t = (1, 2, 3)
print("Tuple:", t)
print("Type:", type(t))
print("Memory address:", id(t))
lst = list(t)
print("Converted to list:", lst)
print("Type now:", type(lst))
print("Memory address:", id(lst))
lst.append(4)
print("After append:", lst)